FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=JimmyEfendy7
ENV N8N_BASIC_AUTH_PASSWORD=n8nrailwayv2aiagent

ENV N8N_HOST=0.0.0.0

ENV N8N_RUNNERS_ENABLED=true

EXPOSE 5678

CMD ["sh", "-c", "n8n start --port ${PORT:-5678}"]
